subcomponents:
  project-jackson:
    subcomponents:
      services:
        subcomponents:
          project-jackson:
            subcomponents:
              jackson-api:
                subcomponents:
                  stable:
                    config:
                      image:
                        repository: saakhtatestregistry.azurecr.io/jackson-api
                        tag: "18"
