subcomponents:
  project-jackson:
    subcomponents:
      services:
        subcomponents:
          project-jackson:
            subcomponents:
              jackson-api:
                subcomponents:
                  stable:
                    config:
                      image:
                        repository: saakhtatestregistry.azurecr.io/jackson-api
                        tag: 27-master-42927eb
              jackson-ui:
                subcomponents:
                  stable:
                    config:
                      image:
                        repository: saakhtatestregistry.azurecr.io/jackson-ui
                        tag: 32-master-95c932a
